
title: Ashley Wenwa - Cybersecurity Portfolio
description: Personal portfolio showcasing projects, labs, and resume
url: https://wenwa444.github.io
baseurl: ""

name: Ashley Wenwa
tagline: Cloud Security | SIEM | CyberShujaa Certified
email: wenwaashley@gmail.com
phone: 0787998416
linkedin: https://www.linkedin.com/in/ashley-wenwa
github: https://github.com/WENWA444

photo: /assets/images/ashley-photo.jpg
